on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

name: Run

jobs:
  run:
    name: Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run Script
        run: cargo run

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { owner, repo } = context.repo
            await github.git.repos.deleteRef({ owner, repo, ref: "tags/latest" })
