on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

name: Run

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      # - name: Get Rust Toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable

      # - name: Run Script
      #   run: cargo run

      - name: Update Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { owner, repo } = context.repo

            const ref = "tags/latest"

            const commits = await github.rest.repos.listCommits({ owner, repo })
            const sha = commits.data[0].sha

            await github.rest.git.createRef({ owner, repo, ref, sha })
