on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

name: Run

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      # - name: Get Rust Toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable

      # - name: Run Script
      #   run: cargo run

      - name: Update Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { owner, repo } = context.repo

            await github.rest.git.deleteRef({ owner, repo, ref: "tags/latest" })

            await github.rest.git.createRef({ owner, repo, ref: "refs/tags/latest", sha: context.sha })

            const { data: { id } } = await github.rest.repos.getLatestRelease({ owner, repo })
            await github.rest.repos.deleteRelease({ owner, repo, release_id: id })

            const release = await github.rest.repos.createRelease({ owner, repo, tag_name: "latest", name: "Latest Release", body: "Latest Release", draft: false })

            const fs = require("fs")

            fs.readFile('README.md', 'utf8', function(err, data){ console.log(data) })

          # await github.rest.repos.uploadReleaseAsset({ owner, repo, release_id: release.data.id, name: "chives.csv", data: "chives.csv" })
